readAC <- function(){
  setwd("~/ACNH-Catalog-Study/ACNH_Catalog")
  Accessories <- read_csv("accessories.csv")
  Achievments <- read_csv("achievements.csv")
  Art <- read_csv("art.csv")
  Bags <- read_csv("bags.csv")
  Bottoms <- read_csv("bottoms.csv")
  Construction <- read_csv("construction.csv")
  DressUp <- read_csv("dress-up.csv")
  Fencing <- read_csv("fencing.csv")
  Fish <- read_csv("fish.csv")
  Floors <- read_csv("floors.csv")
  Fossils <- read_csv("fossils.csv")
  Headwear <- read_csv("headwear.csv")
  Housewares <- read_csv("housewares.csv")
  Insects <- read_csv("insects.csv")
  Misc <- read_csv("miscellaneous.csv")
  Music <- read_csv("music.csv")
  Other <- read_csv("other.csv")
  Photos <- read_csv("photos.csv")
  Posters <- read_csv("posters.csv")
  Reactions <- read_csv("reactions.csv")
  Recipies <- read_csv("recipes.csv")
  Rugs <- read_csv("rugs.csv")
  Shoes <- read_csv("shoes.csv")
  Socks <- read_csv("socks.csv")
  Tools <- read_csv("tools.csv")
  Tops <- read_csv("tops.csv")
  Umbrellas <- read_csv("umbrellas.csv")
  Villagers <- read_csv("villagers.csv")
  WallMounted <- read_csv("wall-mounted.csv")
  Wallpaper <- read_csv("wallpaper.csv")
  setwd("~/ACNH-Catalog-Study/")
}
